In [8]:
from sklearn.datasets import load_iris
import numpy as np

In [11]:
def minkowski_distance(x, y, q):
    return np.sum(np.abs(x - y) ** q, axis=1) ** (1 / q)

In [12]:
# Load the Iris dataset
iris = load_iris()
data = iris.data

# Calculate the Euclidean distance matrix
distance_matrix = minkowski_distance(data[:, np.newaxis, :], data[np.newaxis, :, :], q=2)

# Print the distance matrix
print("Euclidean Distance Matrix:")
print(distance_matrix)

Euclidean Distance Matrix:
[[13.60330842  7.59605161 36.03262411 15.37432925]
 [15.35089574  5.36656315 36.03262411 15.37432925]
 [17.26991604  5.6        37.02148025 15.37432925]
 [18.27703477  5.34602656 35.05866512 15.37432925]
 [14.45164351  8.51351866 36.03262411 15.37432925]
 [11.47388339 11.61120149 33.16066947 13.50592463]
 [18.27703477  6.77642974 36.03262411 14.41839103]
 [14.45164351  6.77642974 35.05866512 15.37432925]
 [20.36295656  5.65862174 36.03262411 15.37432925]
 [15.35089574  5.34602656 35.05866512 16.36612355]
 [11.47388339  9.5005263  35.05866512 15.37432925]
 [16.29263637  6.77642974 34.10087975 15.37432925]
 [16.29263637  5.36656315 36.03262411 16.36612355]
 [21.43478481  5.36656315 39.03933913 16.36612355]
 [10.12175874 12.71219887 38.02407132 15.37432925]
 [10.25914226 17.28351816 35.05866512 13.50592463]
 [11.47388339 11.61120149 37.02148025 13.50592463]
 [13.60330842  7.59605161 36.03262411 14.41839103]
 [10.25914226 10.5375519  33.16066947 14.41839103]
 [13