In [1]:
import numpy as np

In [2]:
def compute_covariance_matrix(feature_matrix):
    # Number of samples
    N = feature_matrix.shape[1]
    
    # Mean of each feature
    mean_vector = np.mean(feature_matrix, axis=1).reshape(-1, 1)
    
    # Subtract mean from each feature
    centered_matrix = feature_matrix - mean_vector
    
    # Compute covariance matrix
    covariance_matrix = np.dot(centered_matrix, centered_matrix.T) / (N - 1)
    
    return covariance_matrix

In [3]:
def compute_correlation_matrix(feature_matrix):
    # Number of samples
    N = feature_matrix.shape[1]
    
    # Mean of each feature
    mean_vector = np.mean(feature_matrix, axis=1).reshape(-1, 1)
    
    # Subtract mean from each feature
    centered_matrix = feature_matrix - mean_vector
    
    # Compute covariance matrix
    covariance_matrix = np.dot(centered_matrix, centered_matrix.T) / (N - 1)
    
    # Compute standard deviations of each feature
    std_devs = np.sqrt(np.diagonal(covariance_matrix))
    
    # Compute correlation matrix
    correlation_matrix = covariance_matrix / np.outer(std_devs, std_devs)
    
    return correlation_matrix

In [13]:
feature_matrix = np.array([[0.5, 1.2, 3.4], [4.1, 2.5, 2.6], [8.7, 5.5, 9.9]])

In [14]:
# Compute the covariance matrix
covariance_matrix = compute_covariance_matrix(feature_matrix)
print("Covariance Matrix:")
print(covariance_matrix)

Covariance Matrix:
[[ 2.29       -0.875       1.82      ]
 [-0.875       0.80333333  0.62666667]
 [ 1.82        0.62666667  5.17333333]]


In [15]:
# Compute the correlation matrix
correlation_matrix = compute_correlation_matrix(feature_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Correlation Matrix:
[[ 1.         -0.64512284  0.52877196]
 [-0.64512284  1.          0.30739972]
 [ 0.52877196  0.30739972  1.        ]]


In [16]:
#The covariance matrix provides information about the linear relationship between pairs of features
#The diagonal elements represent the variance of each feature, while off-diagonal elements represent the covariance between features.


#The correlation matrix provides information about the strength and direction of the linear relationship between pairs of features, standardized by their individual variances.
#Values range between -1 and 1, where 1 indicates a perfect positive correlation, -1 indicates a perfect negative correlation, and 0 indicates no correlation.